{{- $appName := include "rails-app.name" . }}
{{- $description := .Values.appDescription }}
{{- $chart := include "rails-app.chart" . }}
{{- $annotations := include "rails-app.annotations" . }}
{{- $releaseName := .Release.Name }}
{{- $releaseService := .Release.Service }}
{{- if .Values.secret.enabled }}
{{- $scope := .Values.secret.scope }}
{{- range .Values.secret.files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ $appName }}-{{ .name }}'
  annotations:
    description: {{ $description }}
  labels:
    app: '{{ $appName }}'
    chart: '{{ $chart }}'
    scope: {{ $scope }}
    release: "{{ $releaseName }}"
    heritage: "{{ $releaseService }}"
type: Opaque
data:
  {{ .filename }}: {{ .content | b64enc }}
{{- end }}
{{- end }}