apiVersion: v1
kind: Service
metadata:
  name: {{ include "rails-app.fullname" . }}
  annotations:
    {{- include "rails-app.annotations" . | nindent 8 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: {{ include "rails-app.name" . }}
